### ISSUE TITLE
Room layouts specific to rooms

### ISSUE THREAD

**Issue by kcits** [neokoenig/RoomBooking#28]
Ability to set room layouts to specific rooms or limit what layouts are allowed for any specific room.

Example:
Room 101 - can only be a lab
Redwood - can me Boardroom or Lecture
Conference Room C - can be all

**Comment by neokoenig** [comment]
Should be do-able - would probably implement this so that we'd keep the default settings as is, then allow a per location override of potential room layouts. Would then need a JS call to replace the dropdown when switching locations.

**Comment by neokoenig** [comment]
Done in 1.2Dev. Needs documenting + adding to .sql
