### ISSUE TITLE
Expand list filter, to include searching title and multiple months

### ISSUE THREAD

**Issue by kcits** [neokoenig/RoomBooking#31]
Include the ability to search for an Event.  A whole new search functionality/page could be created, but looking at the Listing w/ Filter (/index.cfm/bookings/list) the Filter could be expanded to include a textbox that would search the list and filter the results.

With this, changing/adding the functionality to include multiple months or just all months.

**Comment by neokoenig** [comment]
filter now has date range in 1.2Dev which is probably more useful, also supports multiple locations. Need to add a search function though.
