### ISSUE TITLE
There was an Error while fetching events

### ISSUE THREAD

**Issue by yousafriaz** [neokoenig/RoomBooking#33]
ColdFusion 10 , MYSQL , Installation was successful 

Always getting this warning : Warnings: 	The FlashWrapper plugin may be incompatible with this version of Wheels, please look for a compatible version of the plugin

and Constant Alert Error :  There was an Error while fetching events . 
![capture](https://cloud.githubusercontent.com/assets/4184671/7940425/b815d8e6-091e-11e5-9e13-7b4ee71855ad.PNG)

**Comment by neokoenig** [comment]
"The FlashWrapper plugin may be incompatible with this version of Wheels, please look for a compatible version of the plugin" - ignore this, it's just the plugin manager throwing a warning as the plugin author hasn't updated the version number.

Re: error fetching events - this means the AJAX call to grab the events json is failing.
Have you got URL rewriting enabled? If not there's a chance it may fail (I can't remember, but I may have hardcoded the the URL). Either way, open the console and look at the response coming back - there should be an error message...

**Comment by yousafriaz** [comment]
This is what I am getting from firebug . 

![capture](https://cloud.githubusercontent.com/assets/4184671/7941006/6167c456-0922-11e5-9e37-0abbd854b7f0.PNG)

**Comment by neokoenig** [comment]
That's odd: the formatjson bit is a URL param - i.e `?format=json`

On line 48 of /views/bookings/index.cfm, what does url: mainDataURL + "#params.key#" + "?format=json" render  as?

i.e, do view source, and look for the Event Sources block  - what's in there?

**Comment by neokoenig** [comment]
Also, what's the *actual* url being fired at? It *should* be `/eventdata/get-events/?format=json`

**Comment by yousafriaz** [comment]
![capture](https://cloud.githubusercontent.com/assets/4184671/7941266/122976bc-0924-11e5-9255-15b694fa9ff6.PNG)

![capture1](https://cloud.githubusercontent.com/assets/4184671/7941290/3936e802-0924-11e5-8def-09302fdff156.PNG)

![capture2](https://cloud.githubusercontent.com/assets/4184671/7941295/4b4f072c-0924-11e5-9fe3-18abaa0d2b40.PNG)

**Comment by neokoenig** [comment]
Yep, you've not got URL rewriting enabled on your local server. the web.config file (https://github.com/neokoenig/RoomBooking/blob/master/web.config) should kick in if it's installed in IIS - see http://www.iis.net/downloads/microsoft/url-rewrite to install the extension.

**Comment by yousafriaz** [comment]
Would this application only work with urlrewrite module enabled ?

**Comment by yousafriaz** [comment]
Ok , I have installed URL rewrite module. added web.config file to the wwwroot/roombooking/ folder its contains same code from https://github.com/neokoenig/RoomBooking/blob/master/web.config 
and still getting the same error , below is the response 
![capture1](https://cloud.githubusercontent.com/assets/4184671/7942573/f24a1424-092c-11e5-9744-f3304f64e0d9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4184671/7942584/0152063e-092d-11e5-87b3-1582ee1b9f6b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/4184671/7942599/1e712db2-092d-11e5-877f-468268d40b59.PNG)

![capture](https://cloud.githubusercontent.com/assets/4184671/7942551/dd105c4e-092c-11e5-8d30-925764761f04.PNG)

**Comment by neokoenig** [comment]
Try turning off CF debugging, that will break JSON responses.

**Comment by yousafriaz** [comment]
Alright Finally that did the trick :) thanks a lot for your prompt help and support ! ! 
final questions , is there a way to make it open system ? so user can book room without log in .

**Comment by neokoenig** [comment]
Great stuff.

Yes, you can make the system open by visiting the settings > permissions section - set allowRoomBooking & viewRoomBooking for the 'guest' role (which is the anonymous role)

**Comment by neokoenig** [comment]
PS, I wouldn't particularly recommend it, as there would be no way of stopping spam etc.

**Comment by yousafriaz** [comment]
I have made one change otherwise was unable to create the booking , in the code its was formatdate instead of _formatdate /views/email/bookingnotify,cfm

![capture](https://cloud.githubusercontent.com/assets/4184671/7943197/0b060ff0-0931-11e5-824c-be6e7e197839.PNG)

**Comment by yousafriaz** [comment]
so admin will first create the user account and then user will be able to make the booking or users can create accounts themselves also ?

**Comment by neokoenig** [comment]
Users can't create their own accounts -it's not setup that way really. It was designed more as an internal / intranet style system. You either make the booking form public so anyone can do it, or restrict it to standard users and above.
