### ISSUE TITLE
i8n Multi Language support

### ISSUE THREAD

**Issue by neokoenig** [neokoenig/RoomBooking#38]
Would be nice to translate the whole thing. Not a small amount of work though. Shall see if I can at least get it in place for 1.3

**Comment by neokoenig** [comment]
Note to self; need to match the lang availability for fullcalendar, and load in respective lang files - http://fullcalendar.io/docs/text/lang/  & http://fullcalendar.io/js/fullcalendar-2.3.1/demos/languages.html

**Comment by tapirus** [comment]
Hi Tom, if you would like to have it translated to german, drop me a line. T.

**Comment by neokoenig** [comment]
Awesome, yes, almost definitely will!

**Comment by neokoenig** [comment]
Started on this in the 1.3Dev branch, so @tapirus , if you're genuinely bored.. see https://github.com/neokoenig/RoomBooking/blob/1.3dev/plugins/localizator/locales/de_DE.cfm

**Comment by tapirus** [comment]
You got a merge request. ;-)Thorsten 


     Tom King <notifications@github.com> schrieb am 18:53 Mittwoch, 8.Juli 2015:
   

 Started on this in the 1.3Dev branch, so @tapirus , if you're genuinely bored.. see https://github.com/neokoenig/RoomBooking/blob/1.3dev/plugins/localizator/locales/de_DE.cfm —

**Comment by neokoenig** [comment]
odd, can't see any pull requests?

**Comment by tapirus** [comment]
Strange.Just in case I saved the file in the Editor.
<cfset loc[""] = "">
<cfset loc["Account Listings"] = "Kontoeinträge">
<cfset loc["Actions"] = "Aktionen">
<cfset loc["Activity"] = "Aktivität">
<cfset loc["Address 1"] = "Adresse 1">
<cfset loc["Address 2"] = "Adresse 2">
<cfset loc["All Locations"] = "Alle Orte">
<cfset loc["All Resources"] = "Alle Resourcen">
<cfset loc["any"] = "beliebig">
<cfset loc["API Token"] = "API Token">
<cfset loc["API useage requires a token to be created for your account. Administrators, or those with user creation privledges can create these for you on request"] = "">
<cfset loc["Approve?"] = "Bestätigen?">
<cfset loc["Are you sure you want to disable this account?"] = "">
<cfset loc["Are you Sure?"] = "Sind Sie sicher?">
<cfset loc["Available Locations"] = "Verfügbare Orte">
<cfset loc["Available"] = "Verfügbar">
<cfset loc["Book a Room"] = "Buchen Sie einen Raum">
<cfset loc["Bookable Resources"] = "Buchbare Resourcen">
<cfset loc["Building"] = "Gebäude">
<cfset loc["Bulk Create Events"] = "">
<cfset loc["Calendar"] = "Kalender">
<cfset loc["Careful!"] = "Vorsichtig!">
<cfset loc["Change Password"] = "Passwort ändern">
<cfset loc["Class"] = "Klasse">
<cfset loc["Classname used to assign a colour, should be unique to this location"] = "">
<cfset loc["Clone"] = "Duplizieren">
<cfset loc["Close"] = "Schließen">
<cfset loc["Colour"] = "Farbe">
<cfset loc["Configuration"] = "Konfiguration">
<cfset loc["Confirm Password"] = "Passwort bestätigen">
<cfset loc["Contact Details"] = "Kontaktdetails">
<cfset loc["Contact Name"] = "Kontaktname">
<cfset loc["Country"] = "Land">
<cfset loc["Create Account"] = "Konto erstellen">
<cfset loc["Create And Auto-approve Booking"] = "Erstelle und autobestätige eine Buchung">
<cfset loc["Create New Account"] = "Erstelle ein neues Konto">
<cfset loc["Create New Event"] = "Erstelle eine neue Veranstaltung">
<cfset loc["Create New Location"] = "Erstelle einen neuen Ort">
<cfset loc["Create New Resource"] = "Erstelle eine neue Resource">
<cfset loc["CSS Class"] = "CSS-Klasse">
<cfset loc["Ctrl+click to select multiple locations"] = "Ctrl+Klick um mehrere Orte zu wählen">
<cfset loc["Custom Fields"] = "">
<cfset loc["Data Feed"] = "Datenfeed">
<cfset loc["Data Feeds for your account"] = "Datenfeeds für Ihr Konto">
<cfset loc["Date"] = "Datum">
<cfset loc["Delete"] = "Löschen">
<cfset loc["Deny & Delete"] = "Ablehnen & Löschen">
<cfset loc["Deny"] = "Ablehnen">
<cfset loc["Description"] = "Beschreibung">
<cfset loc["Details"] = "Details">
<cfset loc["Disable"] = "Deaktivieren">
<cfset loc["Displays"] = "Anzeigen">
<cfset loc["Don't Repeat"] = "Nicht wiederholen">
<cfset loc["E-mail"] = "E-Mail">
<cfset loc["Edit"] = "Bearbeiten">
<cfset loc["Editing Event"] = "Veranstaltung bearbeiten">
<cfset loc["Email"] = "E-Mail">
<cfset loc["Ends"] = "Ended">
<cfset loc["Error"] = "Fehler">
<cfset loc["Event Detail"] = "Veranstaltungsdetail">
<cfset loc["Event Details"] = "Veranstaltungsdetails">
<cfset loc["Event Title"] = "Veranstaltungstitel">
<cfset loc["Events ({variable}) records"] = "({variable}) Veranstaltungseinträge">
<cfset loc["Events"] = "Veranstaltungen">
<cfset loc["Feed Name"] = "Feedname">
<cfset loc["Filter"] = "Filter">
<cfset loc["First Name"] = "Vorname">
<cfset loc["Forgot your password?"] = "Passwort vergessen?">
<cfset loc["From"] = "Von">
<cfset loc["Grouping"] = "Groupieren">
<cfset loc["HEX Colour"] = "HEX-Farbe">
<cfset loc["How Many More Times?"] = "Wie viele Male noch?">
<cfset loc["iCal"] = "iCal">
<cfset loc["ID"] = "ID">
<cfset loc["Item is already reserved for another booking!"] = "">
<cfset loc["Keyword"] = "Schlüselwort">
<cfset loc["Language"] = "Sprache">
<cfset loc["Last Name"] = "Nachname">
<cfset loc["Layout"] = "Layout">
<cfset loc["Layouts"] = "Layoute">
<cfset loc["List of possible layouts (optional)"] = "Liste möglicher Layoute (optional">
<cfset loc["List"] = "Liste">
<cfset loc["Location"] = "Ort">
<cfset loc["Locations"] = "Orte">
<cfset loc["Login"] = "Anmelden">
<cfset loc["Logout"] = "Abmelden">
<cfset loc["Logs"] = "Logs">
<cfset loc["Might be a floor or other description"] = "">
<cfset loc["Monthly"] = "monatlich">
<cfset loc["More Information"] = "Mehr Information">
<cfset loc["My Account"] = "Mein Konto">
<cfset loc["Name"] = "Name">
<cfset loc["New Location"] = "Neuer Ort">
<cfset loc["New Resource"] = "Neue Resource">
<cfset loc["Next"] = "Nächste/r">
<cfset loc["No events returned for that date range"] = "Keine Veranstaltungen in diesem Zeitraum zurückgegeben">
<cfset loc["No Events"] = "Keine Veranstaltungen">
<cfset loc["Only allow the resource to be booked in these locations: ctrl+click to multiple select"] = "">
<cfset loc["Parent Building (optional)"] = "">
<cfset loc["Password"] = "Passwort">
<cfset loc["Pending Approval"] = "Ausstehende Bestätigung">
<cfset loc["Permissions"] = "Berechtigungen">
<cfset loc["Phone"] = "Telefonnummer">
<cfset loc["Please delete or rename the <code>/install/</code> directory before continuing"] = "">
<cfset loc["Postcode"] = "Postleitzahl">
<cfset loc["Re-Generate API Key"] = "Regenerierung des API-Schlüssels">
<cfset loc["Remember my email"] = "">
<cfset loc["Request Booking"] = "Buchung anfragen">
<cfset loc["Requested Resources"] = "Angefragte Resourcen">
<cfset loc["Reset"] = "Zurücksetzen">
<cfset loc["Resources can exist in two states, unique or generic; A unique item can't be booked out if it's already associated with a booking going on at that time. A generic item has no such restrictions. e.g: 'My Shiny MacBook Pro' would be a unique item - there's only one of them, whereas 'Laptop' would just imply the user needs 'a laptop'"] = "">
<cfset loc["Resources"] = "Resourcen">
<cfset loc["Restrict Resource to locations"] = "Schränke Resource auf Orte ein">
<cfset loc["Restrict to these locations"] = "Auf diese Orte einschränken">
<cfset loc["Restricted"] = "Eingeschränkt">
<cfset loc["Role"] = "Rolle">
<cfset loc["RSS"] = "RSS">
<cfset loc["Selection is restricted to certain locations"] = "Auswahlist beschränkt auf bestimmte Orte">
<cfset loc["Settings"] = "Einstellungen">
<cfset loc["Sign in"] = "Anmelden">
<cfset loc["Sorry!"] = "Entschuldigung!">
<cfset loc["Starts"] = "Beginnt">
<cfset loc["State/County"] = "Land/Region">
<cfset loc["Tel No."] = "Telefonnummer">
<cfset loc["The colour assigned to this location"] = "Die Farbe, die diesem Ort zugeordnet ist">
<cfset loc["The Main room name, i.e Seminar Room 1"] = "Der Name des Hauptraums, z.B. Seminarraum 1">
<cfset loc["these URLs provide authenticated read only access to forthcoming events: only use or share them with trusted users. Administrators can revoke access to feeds by regenerating API keys"] = "">
<cfset loc["This booking is pending approval from an administrator"] = "Diese Buchung wartet auf eine Bestätigung durch einen Administrator.">
<cfset loc["Time"] = "Uhrzeit">
<cfset loc["Title"] = "Titel">
<cfset loc["To"] = "An">
<cfset loc["Today"] = "Heute">
<cfset loc["Type"] = "Art">
<cfset loc["Unique Item"] = "Einzigartiges Objekt">
<cfset loc["Unique"] = "Einzigartig">
<cfset loc["Upcoming Events"] = "Kommende Veranstaltungen">
<cfset loc["Update Booking"] = "Buchung aktualisieren">
<cfset loc["Update My Details"] = "Aktualisiere meine Details">
<cfset loc["Update Resource"] = "Resource aktualisieren">
<cfset loc["Users"] = "Benutzer">
<cfset loc["Version"] = "Version">
<cfset loc["Weekly"] = "Wöchentlich">
<cfset loc["Will not allow concurrent booking"] = "Erlaubt keine gleichzeitige Buchung">
<cfset loc["You do not have an API token associated with your account today"] = "Sie haben mit Ihrem heutigen Konto kein API-Token verbunden">
<cfset loc["You must enter a start and end date/time before attempting to book this resource"] = "Sie müssen eine Anfangs- und Endzeit vor dem Buchungsversuch dieser Resource eintragen">
<cfset loc["Update Password"] = "Passwort aktualisieren">
<cfset loc["View"] = "Anzeigen">
<cfset loc["You do not have an API token associated with your account"] = "Sie haben kein mit Ihrem Konto verbundenes API-Token ">
<cfset loc["This is an all day event"] = "Dies ist eine ganztägige Veranstaltung">
<cfset loc["Send Confirmation Email to Contact"] = "Sende Bestätigungs-E-Mail an Kontakt"> 


     Tom King <notifications@github.com> schrieb am 12:44 Donnerstag, 9.Juli 2015:
   

 odd, can't see any pull requests?—

**Comment by tapirus** [comment]
another question.In german we do have two forms for "you". The informal one, Facebook would use and the formal one the Business world uses.Which one would you prefer for the Translation? 


     Thorsten Eilers <thorsten_eilers@yahoo.com> schrieb am 16:39 Donnerstag, 9.Juli 2015:
   

 Strange.Just in case I saved the file in the Editor.
<cfset loc[""] = "">
<cfset loc["Account Listings"] = "Kontoeinträge">
<cfset loc["Actions"] = "Aktionen">
<cfset loc["Activity"] = "Aktivität">
<cfset loc["Address 1"] = "Adresse 1">
<cfset loc["Address 2"] = "Adresse 2">
<cfset loc["All Locations"] = "Alle Orte">
<cfset loc["All Resources"] = "Alle Resourcen">
<cfset loc["any"] = "beliebig">
<cfset loc["API Token"] = "API Token">
<cfset loc["API useage requires a token to be created for your account. Administrators, or those with user creation privledges can create these for you on request"] = "">
<cfset loc["Approve?"] = "Bestätigen?">
<cfset loc["Are you sure you want to disable this account?"] = "">
<cfset loc["Are you Sure?"] = "Sind Sie sicher?">
<cfset loc["Available Locations"] = "Verfügbare Orte">
<cfset loc["Available"] = "Verfügbar">
<cfset loc["Book a Room"] = "Buchen Sie einen Raum">
<cfset loc["Bookable Resources"] = "Buchbare Resourcen">
<cfset loc["Building"] = "Gebäude">
<cfset loc["Bulk Create Events"] = "">
<cfset loc["Calendar"] = "Kalender">
<cfset loc["Careful!"] = "Vorsichtig!">
<cfset loc["Change Password"] = "Passwort ändern">
<cfset loc["Class"] = "Klasse">
<cfset loc["Classname used to assign a colour, should be unique to this location"] = "">
<cfset loc["Clone"] = "Duplizieren">
<cfset loc["Close"] = "Schließen">
<cfset loc["Colour"] = "Farbe">
<cfset loc["Configuration"] = "Konfiguration">
<cfset loc["Confirm Password"] = "Passwort bestätigen">
<cfset loc["Contact Details"] = "Kontaktdetails">
<cfset loc["Contact Name"] = "Kontaktname">
<cfset loc["Country"] = "Land">
<cfset loc["Create Account"] = "Konto erstellen">
<cfset loc["Create And Auto-approve Booking"] = "Erstelle und autobestätige eine Buchung">
<cfset loc["Create New Account"] = "Erstelle ein neues Konto">
<cfset loc["Create New Event"] = "Erstelle eine neue Veranstaltung">
<cfset loc["Create New Location"] = "Erstelle einen neuen Ort">
<cfset loc["Create New Resource"] = "Erstelle eine neue Resource">
<cfset loc["CSS Class"] = "CSS-Klasse">
<cfset loc["Ctrl+click to select multiple locations"] = "Ctrl+Klick um mehrere Orte zu wählen">
<cfset loc["Custom Fields"] = "">
<cfset loc["Data Feed"] = "Datenfeed">
<cfset loc["Data Feeds for your account"] = "Datenfeeds für Ihr Konto">
<cfset loc["Date"] = "Datum">
<cfset loc["Delete"] = "Löschen">
<cfset loc["Deny & Delete"] = "Ablehnen & Löschen">
<cfset loc["Deny"] = "Ablehnen">
<cfset loc["Description"] = "Beschreibung">
<cfset loc["Details"] = "Details">
<cfset loc["Disable"] = "Deaktivieren">
<cfset loc["Displays"] = "Anzeigen">
<cfset loc["Don't Repeat"] = "Nicht wiederholen">
<cfset loc["E-mail"] = "E-Mail">
<cfset loc["Edit"] = "Bearbeiten">
<cfset loc["Editing Event"] = "Veranstaltung bearbeiten">
<cfset loc["Email"] = "E-Mail">
<cfset loc["Ends"] = "Ended">
<cfset loc["Error"] = "Fehler">
<cfset loc["Event Detail"] = "Veranstaltungsdetail">
<cfset loc["Event Details"] = "Veranstaltungsdetails">
<cfset loc["Event Title"] = "Veranstaltungstitel">
<cfset loc["Events ({variable}) records"] = "({variable}) Veranstaltungseinträge">
<cfset loc["Events"] = "Veranstaltungen">
<cfset loc["Feed Name"] = "Feedname">
<cfset loc["Filter"] = "Filter">
<cfset loc["First Name"] = "Vorname">
<cfset loc["Forgot your password?"] = "Passwort vergessen?">
<cfset loc["From"] = "Von">
<cfset loc["Grouping"] = "Groupieren">
<cfset loc["HEX Colour"] = "HEX-Farbe">
<cfset loc["How Many More Times?"] = "Wie viele Male noch?">
<cfset loc["iCal"] = "iCal">
<cfset loc["ID"] = "ID">
<cfset loc["Item is already reserved for another booking!"] = "">
<cfset loc["Keyword"] = "Schlüselwort">
<cfset loc["Language"] = "Sprache">
<cfset loc["Last Name"] = "Nachname">
<cfset loc["Layout"] = "Layout">
<cfset loc["Layouts"] = "Layoute">
<cfset loc["List of possible layouts (optional)"] = "Liste möglicher Layoute (optional">
<cfset loc["List"] = "Liste">
<cfset loc["Location"] = "Ort">
<cfset loc["Locations"] = "Orte">
<cfset loc["Login"] = "Anmelden">
<cfset loc["Logout"] = "Abmelden">
<cfset loc["Logs"] = "Logs">
<cfset loc["Might be a floor or other description"] = "">
<cfset loc["Monthly"] = "monatlich">
<cfset loc["More Information"] = "Mehr Information">
<cfset loc["My Account"] = "Mein Konto">
<cfset loc["Name"] = "Name">
<cfset loc["New Location"] = "Neuer Ort">
<cfset loc["New Resource"] = "Neue Resource">
<cfset loc["Next"] = "Nächste/r">
<cfset loc["No events returned for that date range"] = "Keine Veranstaltungen in diesem Zeitraum zurückgegeben">
<cfset loc["No Events"] = "Keine Veranstaltungen">
<cfset loc["Only allow the resource to be booked in these locations: ctrl+click to multiple select"] = "">
<cfset loc["Parent Building (optional)"] = "">
<cfset loc["Password"] = "Passwort">
<cfset loc["Pending Approval"] = "Ausstehende Bestätigung">
<cfset loc["Permissions"] = "Berechtigungen">
<cfset loc["Phone"] = "Telefonnummer">
<cfset loc["Please delete or rename the <code>/install/</code> directory before continuing"] = "">
<cfset loc["Postcode"] = "Postleitzahl">
<cfset loc["Re-Generate API Key"] = "Regenerierung des API-Schlüssels">
<cfset loc["Remember my email"] = "">
<cfset loc["Request Booking"] = "Buchung anfragen">
<cfset loc["Requested Resources"] = "Angefragte Resourcen">
<cfset loc["Reset"] = "Zurücksetzen">
<cfset loc["Resources can exist in two states, unique or generic; A unique item can't be booked out if it's already associated with a booking going on at that time. A generic item has no such restrictions. e.g: 'My Shiny MacBook Pro' would be a unique item - there's only one of them, whereas 'Laptop' would just imply the user needs 'a laptop'"] = "">
<cfset loc["Resources"] = "Resourcen">
<cfset loc["Restrict Resource to locations"] = "Schränke Resource auf Orte ein">
<cfset loc["Restrict to these locations"] = "Auf diese Orte einschränken">
<cfset loc["Restricted"] = "Eingeschränkt">
<cfset loc["Role"] = "Rolle">
<cfset loc["RSS"] = "RSS">
<cfset loc["Selection is restricted to certain locations"] = "Auswahlist beschränkt auf bestimmte Orte">
<cfset loc["Settings"] = "Einstellungen">
<cfset loc["Sign in"] = "Anmelden">
<cfset loc["Sorry!"] = "Entschuldigung!">
<cfset loc["Starts"] = "Beginnt">
<cfset loc["State/County"] = "Land/Region">
<cfset loc["Tel No."] = "Telefonnummer">
<cfset loc["The colour assigned to this location"] = "Die Farbe, die diesem Ort zugeordnet ist">
<cfset loc["The Main room name, i.e Seminar Room 1"] = "Der Name des Hauptraums, z.B. Seminarraum 1">
<cfset loc["these URLs provide authenticated read only access to forthcoming events: only use or share them with trusted users. Administrators can revoke access to feeds by regenerating API keys"] = "">
<cfset loc["This booking is pending approval from an administrator"] = "Diese Buchung wartet auf eine Bestätigung durch einen Administrator.">
<cfset loc["Time"] = "Uhrzeit">
<cfset loc["Title"] = "Titel">
<cfset loc["To"] = "An">
<cfset loc["Today"] = "Heute">
<cfset loc["Type"] = "Art">
<cfset loc["Unique Item"] = "Einzigartiges Objekt">
<cfset loc["Unique"] = "Einzigartig">
<cfset loc["Upcoming Events"] = "Kommende Veranstaltungen">
<cfset loc["Update Booking"] = "Buchung aktualisieren">
<cfset loc["Update My Details"] = "Aktualisiere meine Details">
<cfset loc["Update Resource"] = "Resource aktualisieren">
<cfset loc["Users"] = "Benutzer">
<cfset loc["Version"] = "Version">
<cfset loc["Weekly"] = "Wöchentlich">
<cfset loc["Will not allow concurrent booking"] = "Erlaubt keine gleichzeitige Buchung">
<cfset loc["You do not have an API token associated with your account today"] = "Sie haben mit Ihrem heutigen Konto kein API-Token verbunden">
<cfset loc["You must enter a start and end date/time before attempting to book this resource"] = "Sie müssen eine Anfangs- und Endzeit vor dem Buchungsversuch dieser Resource eintragen">
<cfset loc["Update Password"] = "Passwort aktualisieren">
<cfset loc["View"] = "Anzeigen">
<cfset loc["You do not have an API token associated with your account"] = "Sie haben kein mit Ihrem Konto verbundenes API-Token ">
<cfset loc["This is an all day event"] = "Dies ist eine ganztägige Veranstaltung">
<cfset loc["Send Confirmation Email to Contact"] = "Sende Bestätigungs-E-Mail an Kontakt"> 


     Tom King <notifications@github.com> schrieb am 12:44 Donnerstag, 9.Juli 2015:
   

 odd, can't see any pull requests?—

**Comment by neokoenig** [comment]
Probably the formal I'd guess; but really, whatever you think would be most appropriate!

**Comment by tapirus** [comment]
Hi Tom, tried it again. Made two clicks more. Hope this is sufficient. ;-) 


     Tom King <notifications@github.com> schrieb am 18:53 Mittwoch, 8.Juli 2015:
   

 Started on this in the 1.3Dev branch, so @tapirus , if you're genuinely bored.. see https://github.com/neokoenig/RoomBooking/blob/1.3dev/plugins/localizator/locales/de_DE.cfm —

**Comment by neokoenig** [comment]
in 1.3 Dev
