### ISSUE TITLE
MS SQL Server Reserve Words Error

### ISSUE THREAD

**Issue by yiengly** [neokoenig/RoomBooking#49]
Hi,

I am trying to get your application working with MS SQL Server but am running into a few minor issues.

I have converted the mysql query script for new installation to t-sql (ms sql server 2008), but am running into the following issues because they are reserve words:
* 'user' column in the permissions table. 
* 'end' column in the events table

My question are:
* if I change the column 'user' to say, 'userRole' in the sql script, where else in the code do I need to change?
* If change the column 'end' to 'endDate' in the sql script, what do I need to update in the code. I have try a find and replace, but it seems like I am still missing something as I am still getting the error: there was an error fetching the events! when i click on the main page.

When I click on Settings > Users, I get the following error:
Column 'users.email' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause
Location:
Line 83 in controllers\Users.cfc

What do I need to update to resolve?

Appreciate your help.
Yieng

**Comment by neokoenig** [comment]
Hmm, you'd have to change a fair few things I fear;

Changing 'user' column name in the permissions table:
This is just the name of a role, so you could change this relatively easily by just renaming the `user` column to `mainuser` (it's the actual *name* of the role in the column). As long as you've got no existing users in the `user` role, this should actually be fine after a restart of the application.

Change the column 'end' to 'endDate':
This would require a lot more changes;

`/controllers/Eventdata.cfc` - handles the calendar specific data;
 - Basically, any model() call which has `end` in the `where` argument;
 - `prepeventdata()` would need line 87 changing as you're referencing `end` within the `event` model

`/controllers/Bookings.cfc` - the `create()` function - any reference to `nevent.end` , `_agendaListWC()` - `arrayAppend(wc, "end > '#sd#'");` would need changing, `check()`, etc - there are quite a lot which this would affect, as it's the end date for the event/booking, so used a LOT.

`/controllers/Api.cfc` - few in here too

`/eventdata/_details.cfm` has references to the shortcode plugin which would call the field by id

I've made a lot of changes to 1.3dev which would mean you'd need to redo all of this too; If I can find a lot of msSQL reserved words I might be able to put the changes in for the next release: it would be nice to be able to support msSQL, but I don't have any installations to test against.

**Comment by yiengly** [comment]
Tom,
Thanks for your prompt reply. What about this error:

Column 'users.email' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause
Location:
Line 83 in controllers\Users.cfc

btw: I would be happy to help out with MS SQL Server testing, and would be happy to share with you the new-installation.sql script that I converted to t-sql for MS SQL Server.

**Comment by neokoenig** [comment]
Hmm, not sure. Try removing the group="id" attribute (you might get double entries returned, but it would be useful to know whether it's that or not)

**Comment by yiengly** [comment]
I've removed the group="id" attribute as suggested and the error's gone when clicking on the Settings > Users link (for logged in users).

**Comment by yiengly** [comment]
Tom,

I have now resolved all errors. However if I upgrade in the future, I might encounter these errors again? Hopefully these will be taken care of in the next minor version upgrade. Would be good if the reserve words such as 'user' can be escaped for t-sql (ms sql server) by enclosing them with square brackets [].

Also, in the 'permissions' table, i initially rename the 'user' column to 'userAccess', but now i want to rename it to 'users'. However I am getting a message that it can't find the column userAccess when I click on Settings > Users link. 

How would I go about changing it to 'users' assuming this is not a reserve word, and ensure I do not receive the error?

**Comment by yiengly** [comment]
Correction to previous question:

Also, in the 'permissions' table, i initially rename the 'user' column to 'userAccess', but now i want to rename it to 'users'. However I am getting a message that it can't find the column userAccess when I click on Settings > Permissions link.

**Comment by neokoenig** [comment]
You'll need to restart the application if you make any database related changes (i.e ?reload=design&password=roombooking) otherwise the framework won't pick up the changes.

**Comment by yiengly** [comment]
i have now reverted the column name changed for end date from 'endDate' to the original name of 'end' so that we can eliminate this as a source of the issue. 

However I am not getting the following error when loading the main room booking system page:
Pop-up alert:
There was an error while fetching events!

System email message:
Error:
Element COLUMN is undefined in a CFML structure referenced as part of an expression. 
Location:
Line 58 in controllers\Eventdata.cfc

URL:
/roomBooking/index.cfm?controller=eventdata&action=getevents&type=index&key=&format=json 
Referrer:
/roomBooking/index.cfm?controller=bookings&action=index

**Comment by yiengly** [comment]
Don't worry about it. I have now reverted to using 'endDate' for 'end' in the events table.
Now I just need to know why it is not inserting the end date for new event additions.
