### ISSUE TITLE
Edit event

### ISSUE THREAD

**Issue by msslava** [neokoenig/RoomBooking#50]
First of all, thank you for your work!
When you press the edit event, the lost time of the event.
Also, there is no check on the availability of resources.
Thank you!

**Comment by neokoenig** [comment]
I'm afraid I'd need more detail. All these things currently work on the demo site...

**Comment by msslava** [comment]
Ok. I make some changes to your code (primarily related to localization), it can be affected ... I'm sorry, that just does not turn to your demo. In the near future I will check my problem on a clean installation.

**Comment by neokoenig** [comment]
FYI, localisation is coming in 1.3

T

**Comment by msslava** [comment]
Good news. By the way, it is possible to prohibit reservations if events overlap? Now just pops up a warning, but you can book.

**Comment by neokoenig** [comment]
Not at the moment, but I’m looking at that

**Comment by msslava** [comment]
On a clean installation of these problems were detected. So I'm somewhere made a mistake.
