### ISSUE TITLE
Add some functional

### ISSUE THREAD

**Issue by msslava** [neokoenig/RoomBooking#51]
I think if you add some functionality, it will appeal to many users, and make your system more flexible. If you are interested:
1) added to the amount of resources. For example, you have 3 identical notebook. Now you need to add in their 3 times. It is impractical.
2) As I write this, it would be good to ban reservation if events overlap.Now simply displays a pop-up message
3) Setting the SMTP server (for example, Google) through the admin panel. Actually I have not found where you can affect the email, only the address for the notifications and a copy by email.
4) Create a printable version with a full description of the event (It may be by email)
5) Create an event on behalf of any user of the system (only available to the administrator)

Many thanks.
PS. If you need help with translation into Russian, I can help

**Comment by neokoenig** [comment]
Re: SMTP, nine times out of ten this is set globally in the CFIDE or Lucee administrator: but if you need to set it manually, you can in `/config/app.cfm' by adding:

```
	this.tag.mail.server="smtp.mandrillapp.com";
	this.tag.mail.username="you@domain.com";
	this.tag.mail.password="paasdadg";
	this.tag.mail.port=587;
```

These are all pretty good ideas, I'll have a look at how easy they are to implement.

**Comment by msslava** [comment]
Thanks!
