### ISSUE TITLE
No matching function [ADDSHORTCODE] found

### ISSUE THREAD

**Issue by alucard1123** [neokoenig/RoomBooking#52]
I followed the steps on readme and hit the problem when I started program after installing check is all green.Mail says:No matching function [ADDSHORTCODE] found
stack trance is 
string 
    Message 
        string No matching function [ADDSHORTCODE]
found 
    StackTrace 
        string No matching function [ADDSHORTCODE]
found
	at
lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:768):768
	at
lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:742):742
	at
lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1590):1590
	at
events.onapplicationstart_cfm$cf.call(/root/lucee/webapps/ROOT/events/onapplicationstart.cfm:39):39
	at
lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
	at
lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:855):855
	at
wheels.global.cfml_cfm$cf.udfCall1(/root/lucee/webapps/ROOT/wheels/global/cfml.cfm:111):111
	at
wheels.global.cfml_cfm$cf.udfCall(/root/lucee/webapps/ROOT/wheels/global/cfml.cfm):-1
	at
lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at
lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:216):216
	at
lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:775):775
	at
lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:773):773
	at
lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1600):1600
	at
wheels.events.onapplicationstart_cfm$cf.udfCall(/root/lucee/webapps/ROOT/wheels/events/onapplicationstart.cfm:395):395
	at
lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
	at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
	at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
	at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
	at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
	at
lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
	at
lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:405):405
	at
lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:283):283
	at
lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:2842):2842
	at
lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:118):118
	at
lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:35):35
	at
lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2262):2262
	at
lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2225):2225
	at
lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
	at
lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47
	at
javax.servlet.http.HttpServlet.service(HttpServlet.java:725):725
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291):291
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206
	at
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239):239
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206):206
	at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219):219
	at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106):106
	at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501):501
	at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142):142
	at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79):79
	at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610):610
	at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88):88
	at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537):537
	at
org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085):1085
	at
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658):658
	at
org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222):222
	at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556):1556
	at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513):1513
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617
	at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61):61
	at
java.lang.Thread.run(Thread.java:745):745
 
    TagContext Array

please help!! :)

**Comment by neokoenig** [comment]
You need to add the shortcodes plugin: https://github.com/neokoenig/cfwheels-shortcodes

**Comment by alucard1123** [comment]
You are right . the plugin is unzipped to ../root/plugins I copied them to plugin dir and now is working ,thanks :)
