### ISSUE TITLE
email confirmation problem.

### ISSUE THREAD

**Issue by surching4u** [neokoenig/RoomBooking#53]
Hi,
when i add email address while booking it returns following error.

"Error!

Sorry, that caused an unexpected error.
Please try again later. "

And can i add multiple attendees in meeting and share calendar event to them?
Please reply me.

Thanks in advance.

**Comment by neokoenig** [comment]
You've probably not got any SMTP servers setup - add on in either `/CFIDE/administrator` for Adobe ACF, or `/lucee/admin/server.cfm` ; this means you should get error emails too if you've correctly defined an error handling email address in `/config/production/settings.cfm`.

If you just want to see the error on screen for development purposes, reload the application in Design mode using `/?reload=design&password=YOURRELOADPASSWORD`
