### ISSUE TITLE
Toggle debug off on footer

### ISSUE THREAD

**Issue by yiengly** [neokoenig/RoomBooking#56]
Hi Tom,
How do I turn off the application debug info in the footer. It displays the following info:

Application: 	<app id>
Framework: 	CFWheels 1.4.1
Active Environment: 	Design
Host Name: 	<host-name>
CFML Engine: 	Adobe ColdFusion <version number>
Default Data Source: 	<data source name>
Database Adapter: 	<adpater name>
URL Rewriting: 	off
URL Obfuscation: 	Off
Plugins: 	shortcodes
flashwrapper
Route: 	Home
Controller: 	Bookings
Action: 	Index
Key(s): 	
Parameters: 	None

**Comment by neokoenig** [comment]
You've got into design mode where the app is reloaded on every request.

Just do:
`/?reload=production&password=YOURRELOADPASSWORD` to get back to production. 

Also check `/config/environment.cfm` has `<cfset set(environment="production")>`
