### ISSUE TITLE
Multi-day event not indicated across days

### ISSUE THREAD

**Issue by yiengly** [neokoenig/RoomBooking#59]
Hi Tom,

I have a multi-day event but the colour background indicator only shows day 1. If the event was two days, it should cover both days.

I think it might be because I rename 'end' to 'endDate'. Can advise where in the code I need to update the references from 'end' to 'endDate' to resolve this display issue.

Thanks.
Yieng

**Comment by neokoenig** [comment]
Again, you're making a lot of changes to the codebase where I can't see what you've changed, so you're kinda on your own here. If you're in doubt whether something *should* work or not, check roombooking.oxalto.co.uk - if the behaviour is correct, then you know it's your own codebase.
