### ISSUE TITLE
Fresh install error [QueryExecute]

### ISSUE THREAD

**Issue by rory-sm** [neokoenig/RoomBooking#68]
Hello 

I have done a fresh install using 
RoomBooking-1-2-1.zip
Lucee 4.5.4.017 final
Mysql 5.7.17 

I got all GREEN from the install

When I go to the root on webserver I get ....

The Error Occurred in
/data/lucee/tomcat/webapps/ROOT/events/functions.cfm: line 337 
335: @version 1, September 22, 2014
336: --->
337: <cffunction name="QueryExecute" output="false"
338: hint="
339: * result struct is returned to the caller by utilizing URL scope (no prefix needed) *

called from /wheels/global/appfunctions.cfm: line 5 
called from /wheels/functions.cfm: line 7 
called from /Application.cfc: line 2 
called from /Application.cfc: line 1

**Comment by neokoenig** [comment]
You can actually delete/comment out the whole `QueryExecute()` function - that's in the for CF10 compatibility.

Note, I've not tested on mySQL 5.7 - I can't forsee major issues, but just to let you know!

**Comment by rory-sm** [comment]
Hello


Thanks for the quick reply ...


Now I am getting a 500 error


How do I undeploy / redeploy the app ?


Error!

Sorry, that caused an unexpected error.
Please try again later.



last bit of Catalina.log is ..


16-Dec-2016 06:16:05.028 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 16179 ms
Fri Dec 16 06:16:31 EST 2016-179 class lucee.runtime.instrumentation.Agent.getInstrumentation() is not returning a Instrumentation



________________________________

**Comment by neokoenig** [comment]
What does `/WEB-INF/lucee/logs/exception.log` have in it?
`getInstrumentation()` is usually there, not normally an issue.

To restart the app, do `http://yourdomain.com/?reload=design&password=YOURPASSWORD` - in design mode the errors will be output to the screen.

**Comment by rory-sm** [comment]
Hello Tom,


Sorry to be a pain ... but


1) /data/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/logs/exception.log is empty if I

use either


http://ec2-35-160-197-142.us-west-2.compute.amazonaws.com:8888/?reload=design&password=ffff


or go to the root of my site ...


http://ec2-35-160-197-142.us-west-2.compute.amazonaws.com:8888/



There is also /data/lucee/tomcat/webapps/root/WEB-INF/lucee/logs /exception.log ... this is also empty ....


From experimentation the /data/lucee/tomcat/webapps/root appears to be created when tomcat starts




I have set


[cid:077bc8d8-2f49-4bf9-a688-7be287a6232d]


but get nothing in any files in ...


/data/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/logs


I notice that there is repeating ...


/data/lucee/lib/iText-toolbox-2.1.2u.jar (No such file or directory)
/data/lucee/lib/bcmail-jdk14-138.jar (No such file or directory)
/data/lucee/lib/bcprov-jdk14-138.jar (No such file or directory)
/data/lucee/lib/iText-toolbox.jar (No such file or directory)
/data/lucee/lib/iText-toolbox-2.1.2u.jar (No such file or directory)


in the /data/lucee/tomcat/logscatalina.out ...are these critical jar files ?



Rory




________________________________

**Comment by neokoenig** [comment]
No problem;
So the fact you're getting "Sorry, that caused an unexpected error.
Please try again later." means that lucee and the framework is at least loading; so it's really just a matter of finding out what the error is so we can fix it.

The nuclear option is:

Change `/config/environment.cfm` - to `<cfset set(environment="design")>` and then in `/config/app.cfm`, add `<cfset this.name = "roombooking2">` 

Changing the application name will force the app to reload the application framework, and re-pull in the environment: the reason it's not switching is the error is kicking in first.

Then check your lucee install is going to actually output errors: go to `/lucee/admin/server.cfm` and login. Under `settings -> error` check `error-public.cfm` is NOT selected (I think the other two will output stack traces etc. ) - Also, in `Services -> Mail`, check you've actually set an SMTP server - this is a common thing most people new to lucee forget.

The missing JARs shouldn't be a problem - iText is something to do with PDFs I think.

That should at least get you seeing errors on screen. If that really doesn't work, then might be worth restarting the lucee service too.

**Comment by rory-sm** [comment]
Hello Tom,


You are a Star .... the nuke option at least displayed an error


[cid:3421478a-2d17-4d93-95b3-1b16d8bd3320]


and in /data/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/logs/exception.log


"Severity","ThreadID","Date","Time","Application","Message"
"ERROR","http-nio-8888-exec-1","12/18/2016","20:51:38","",";No matching function [ADDSHORTCODE] found;No matching function [ADDSHORTCODE] found
        at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:768):768
        at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:743):743
        at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1596):1596
        at events.onapplicationstart_cfm$cf.call(/events/onapplicationstart.cfm:39):39







________________________________

**Comment by neokoenig** [comment]
Ah plugins. Forgot about those. It's fixed on the master but not 1.2;
Just copy and paste the two zip files here `https://github.com/neokoenig/RoomBooking/tree/master/plugins` and reload the application with `?reload=design&Password=roombooking`

You should be good to go then.

**Comment by rory-sm** [comment]
Hello Tom,


I checked the plugins directory


/data/lucee/tomcat/webapps/ROOT/plugins

and found ...
 4 -rw-r--r--.  1 root root  3328 Jul  1  2015 shortcodes-0.2.zip
 4 -rw-r--r--.  1 root root  3328 Dec 20 05:45 flashwrapper-0.2.zip

I copied
FlashWrapper-0.2.zip
Shortcodes-0.2.zip
from master
into
/data/lucee/tomcat/webapps/ROOT/plugins

I got the same execption ... it is expecting the zip's to be unzpped

Do I need to  unzip these ... if so into what folder

I tried unzipping but got

[cid:aca6c812-eb8e-46ca-883d-4f475254445f]

in /data/lucee/tomcat/webapps/ROOT/plugins/stylesheets there is
bootstrap.min.cfm

Am I missing something ?

Rory

________________________________

**Comment by neokoenig** [comment]
hmm, it should auto unzip;
Either way, just double check the filename matches the folder (there's an annoying case-sensitivity issue in plugins in this version of the framework) - you should have:

```
/plugins/flashwrapper/flashwrapper.cfc
/plugins/shortcodes/shortcodes.cfc
```
If for any reason you have "FlashWrapper.cfc", rename to lowercase.

**Comment by rory-sm** [comment]
Hello ..


I have

.
./FlashWrapper-0.2.zip
./flashwrapper
./flashwrapper/flashwrapper.cfc
./flashwrapper/controller
./flashwrapper/controller/flash.cfm
./shortcodes-0.2.zip
./shortcodes.cfc
./index.cfm
./flashwrapper.cfc
./flashwrapper-0.2.zip
./Shortcodes.cfc
./controller
./controller/flash.cfm
./flashwraper.tar
./shortcodes
./shortcodes/shortcodes.cfc
./Shortcodes-0.2.zip
./FlashWrapper.cfc
./stylesheets
./stylesheets/bootstrap.min.cfm
./shortcodes.tar


 in /data/lucee/tomcat/webapps/ROOT/plugins

but get
invalid component definition, can't find component [plugins.stylesheets.stylesheets]



Rory


________________________________

**Comment by neokoenig** [comment]
Yeah, that's been unzipped incorrectly. This is what you're after:

![image](https://cloud.githubusercontent.com/assets/381268/21348983/8e2dbe84-c6a7-11e6-98af-19c5ac4beeaf.png)

**Comment by msslava** [comment]
I have the same problem. My system:
Windows7, Lucee 4.5.4.017 final, MS SQL. 
I can not run the version 1.2 and 1.3, but when you install all the items marked in green

**Comment by rory-sm** [comment]
Tom

It works !!!!!!

Thanks for your help

The last issue is that I cannot login ...

I can see one user in the dB but don't know the password ... I have not configured email so cannot use the reset password

Can the password be set by some other method ?

Rory
________________________________

**Comment by neokoenig** [comment]
the password would have been whatever you set it to in the `/install/` process.
If you delete the user from the users table and rerun the `/install/` script it should notice you don't have a primary admin user and prompt you to create one.

**Comment by neokoenig** [comment]
@msslava yeah, there's too many issues with MSSQL (turns out I used reserved words etc without realising). I don't use MSSQL at all, and don't have a testing environment for it either.

Someone did actually fix my stuff and blogged about it: https://yiengly.wordpress.com/2015/09/15/install-room-booking-system-on-windows-and-sql-server/ - that might be your best bet.

Version 2.x is definitely dropping support for MSSQL in anyway, and concentrating on mySQL and postgres. Part of the reason is that MSSQL requires a windows server to setup continuous integration via travis CI, whereas open source stuff is easier.

**Comment by msslava** [comment]
@neokoenig Thanks for support! I will to try to fix it using the postgres on Windows. Will it work?

**Comment by neokoenig** [comment]
@msslava Honestly, I have no idea. Never tried!

**Comment by msslava** [comment]
Install mysql server on Windows solved the problem.
