### ISSUE TITLE
Installing RoomBooking on Ubunto

### ISSUE THREAD

**Issue by cbleek** [neokoenig/RoomBooking#72]
Im trying to install RoomBooking on Ubuntu.

There seems to be a problem with http://www.getrailo.org/

Building railo from source fails. Is it in general a good idea to try to install RoomBooking on linux. Or should I look for a Hoster offering Coldfusion. 

Regards,

Carsten

**Comment by neokoenig** [comment]
Use Lucee - http://lucee.org/ instead. Start with lucee 4.5 though, as I can't remember if I've tested on 5.x yet for version 1.x
Railo isn't maintained any more.

**Comment by cbleek** [comment]
Hi Neokoenig,

thanks for the hint. Installation of lucee was strait forward. I unzipped the latest Github release into the webroot of the tomcat. but I got errors.

Would you be able to make the installation on a fresh ubuntu 16.04? I would give you root access to a VM.

Please make me an offer.  You'll find by contact on my Github profile

Regards,

Carsten
