### ISSUE TITLE
install with lucee meet problem

### ISSUE THREAD

**Issue by liketemple** [neokoenig/RoomBooking#75]
install lucee and roombooking successfully, but when go to localhost:8888, meet the error:

The name [QueryExecute] is already used by a built in Function
ROOT/events/functions.cfm: line 337
335: @version 1, September 22, 2014
336: --->
337: <cffunction name="QueryExecute" output="false"
338: hint="

seems define a function use a built in function name.

**Comment by liketemple** [comment]
BTW, the lucee version is 4.5.5.006

**Comment by neokoenig** [comment]
You can actually just remove that function - it's for CF10 compatibility
