### ISSUE TITLE
invalid component definition, can't find component [plugins.stylesheets.stylesheets]

### ISSUE THREAD

**Issue by sokeada** [neokoenig/RoomBooking#76]
Bro, i really like your room booking app, I have tried to install on my Linux server and everything seems smooth but when i open the page, I've got the error "invalid component definition, can't find component [plugins.stylesheets.stylesheets]"

Note: stylesheets directory and file are in its place but the error still appear. Please help. 

Thanks,

Sokeada

![image](https://user-images.githubusercontent.com/23713338/46844934-4e60f180-ce03-11e8-9a4b-091d091fdbeb.png)

**Comment by neokoenig** [comment]
See https://github.com/neokoenig/RoomBooking/issues/68#issuecomment-268220831

**Comment by sokeada** [comment]
Thanks Neokoening for a quick reply. I'm not sure if i did the right thing. Please have a look in the attached. I fell that flashwrapper and index are in stylesheets directory?

![flashwrapper](https://user-images.githubusercontent.com/23713338/46989473-6f895100-d127-11e8-9f8f-bdc10112e3ed.jpg)
![stylesheets](https://user-images.githubusercontent.com/23713338/46989474-6f895100-d127-11e8-8760-37f02b8f95c7.jpg)

**Comment by sokeada** [comment]
I've got it works now bro after moving flashwrapper.cfc and index.cfm to root directory of flashwrapper, thanks you so much for this wonder full app.
![flashwrapperindex](https://user-images.githubusercontent.com/23713338/47001140-f8b67d00-d153-11e8-8a70-c73b8d7539af.jpg)
