### ISSUE TITLE
SMTP Configuration

### ISSUE THREAD

**Issue by sokeada** [neokoenig/RoomBooking#77]
Hi Bro, I could not find the SMTP configuration to send the alert to the admin when booking request has been made, any guide please.

**Comment by neokoenig** [comment]
add on in either `/CFIDE/administrator` for Adobe ACF, or `/lucee/admin/server.cfm` ; this means you should get error emails too if you've correctly defined an error handling email address in `/config/production/settings.cfm`.

Alternatively if you're on lucee, you can specify an SMTP server in `/config/app.cfm` via:
```
<cfscript>
		this.tag.mail.server="smtp.mydomain.com";
		this.tag.mail.username="usernamehere";
		this.tag.mail.password="abc123!";
		this.tag.mail.port=587; // optional
		this.tag.mail.usetls=true; //optional
</cfscript>
```

**Comment by sokeada** [comment]
Bro, i really appreciated your app and support. Would you mind to please point me to the right tool for adding this cfscrip into my Room Booking System?

**Comment by sokeada** [comment]
Hello Bro, could you please help to verify my configuration, am i put it the right place?

![rbs-mail](https://user-images.githubusercontent.com/23713338/49139420-58dc3980-f324-11e8-93eb-0f95c426926f.JPG)

**Comment by neokoenig** [comment]
Assuming you're on lucee, that should work

**Comment by sokeada** [comment]
Yes, i'm on lucee 4.5 so my configuration is correct right? but when i try to add new booking, i don't get any email notification while i already put the receptionist email in the application configuration. Oh one more thing, i have create two users then i used each user to create the booking, i noticed the the booking is auto approved while the permission is set to not auto approve. On the other hand, one user can delete another user's booking and the permission is not allow to. Everything is default from your source, bro.
 
![rbsemail](https://user-images.githubusercontent.com/23713338/49213263-6feb5c00-f3f6-11e8-8058-68466584a47a.JPG)
![rbspermission](https://user-images.githubusercontent.com/23713338/49213523-17688e80-f3f7-11e8-861b-453ced8ec3b6.JPG)

**Comment by neokoenig** [comment]
The `siteEmailAddress` is the "from" address;
The receipt is only sent to the contact - use the BCC function to receive a copy of all bookings.

**Comment by sokeada** [comment]
Thanks bro, i'll try and let you know.

**Comment by sokeada** [comment]
Bro, i have tried as what you said but seems not working, admin, recept and contact, none of them receive any email. I'm not sure if i'm not doing correctly.

![emailrbs](https://user-images.githubusercontent.com/23713338/49277832-8c020280-f4b5-11e8-858d-3b32afeb8a99.JPG)
